triggers:
- description: null
  envs: []
  last_enabled_at: 2024-07-26 13:10:48.537435
  name: datamart_data_type_validation
  pipeline_uuid: datamart_data_type_validation
  schedule_interval: @daily
  schedule_type: time
  settings:
   landing_time_enabled: true
  sla: null
  start_time: 2024-07-26 08:00:00
  status: active
  variables: []
